#!/usr/bin/env bash
# Install NGINX and print "Hello World"

sudo apt-get update
sudo apt-get install -y nginx
sudo mkdir -p /var/www/html
sudo chmod -R 777 /var/www
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
