#!/usr/bin/env bash
# installs nginx and redirects when /redirect_me
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /etc/nginx/sites-available/default
sudo sed -i '/server_name _/a\  location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default
sudo service nginx restart
