#!/usr/bin/env bash
#configure a server to have a custom 404 page
sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 777 /var/www
echo 'Hello World' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/error/404.html
sed -i '/server_name _/a location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default
sed -i '/server_name _/a error_page 404 /404.html; location = /404.html {root /var/www/error/;internal; }' /etc/nginx/sites-available/default
service nginx restart
