#!/usr/bin/env bash
# installs nginx and customs page 404
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir /var/www/error
sudo chmod -R 755 /etc/nginx/sites-available/default
sudo chmod -R 777 /var/www
sudo echo "Ceci n'est pas une page" > /var/www/error/404.html
sudo sed -i '/server_name _/a\  error_page 404 /404.html;\n     location = /404.html {root /var/www/error/;internal; }' /etc/nginx/sites-available/default
sudo service nginx restart
