#!/usr/bin/env bash
# configures web-02 to be identical to web-01
# configures custom response header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /etc/nginx/nginx.conf
sudo sed -i "13i\ add_header X-Served-By '$HOSTNAME';" /etc/nginx/nginx.conf
sudo nginx restart
