#!/usr/bin/env bash
#sets nginx for listening to 80 port
sudo apt update
sudo apt install nginx
ufw allow 'Nginx HTTP'
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
