#!/usr/bin/env bash
# This script prints "bad luck" and "good luck" for 4th and 8th iterations in range of 10
i=1
while [[ $i -lt 11 ]]
do
if [[ $i -eq 4 ]]; then
echo "bad luck"
((i++))
elif [[ $i -eq 8 ]]; then
echo "good luck"
((i++))
else
echo "Best School"
((i++))
fi
done
